from django.urls import path

from .django_views import (
    CaptureStatusView,
    CaptureUploadView,
    CancelView,
    ConsultView,
    ConfirmView,
    ClientCheckView,
    ClientRefreshView,
    FormerRecommendationView,
    LoginView,
    RegenerateSimulationView,
    RecommendationView,
    RegisterView,
    RetryRecommendationView,
    SelectionView,
    SurveyView,
    TrendView,
)
from .admin_views import (
    ActiveClientSessionsView,
    AdminLoginView,
    AdminProfileView,
    AdminRefreshView,
    AdminRegisterView,
    AdminClientDetailView,
    AdminClientRecommendationView,
    AdminDashboardView,
    LegacyAdminClientDetailView,
    LegacyAdminClientAssignView,
    LegacyCustomerProfileNoteView,
    LegacyDesignerDiagnosisCardView,
    LegacyConsultationNoteCreateView,
    LegacyAdminTrendReportView,
    LegacyAllClientsView,
    AdminTrendReportView,
    AllClientsView,
    ConsultationCloseView,
    ConsultationNoteView,
    AdminChatbotAskView,
    AdminAiHealthView,
    StyleReportView,
    DesignerListView,
)

urlpatterns = [
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/refresh/', ClientRefreshView.as_view(), name='client-refresh'),
    path('auth/check/', ClientCheckView.as_view(), name='check'),
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('survey/', SurveyView.as_view(), name='survey'),
    path('capture/upload/', CaptureUploadView.as_view(), name='upload'),
    path('capture/status/', CaptureStatusView.as_view(), name='capture-status'),
    path('analysis/former-recommendations/', FormerRecommendationView.as_view(), name='former-recommendations'),
    path('analysis/recommendations/', RecommendationView.as_view(), name='recommendations'),
    path('analysis/trend/', TrendView.as_view(), name='trend'),
    path('analysis/retry-recommendations/', RetryRecommendationView.as_view(), name='retry-recommendations'),
    path('analysis/regenerate-simulation/', RegenerateSimulationView.as_view(), name='regenerate-simulation'),
    path('analysis/selection/', SelectionView.as_view(), name='selection'),
    path('analysis/confirm/', ConfirmView.as_view(), name='confirm'),
    path('analysis/cancel/', CancelView.as_view(), name='cancel'),
    path('analysis/report/', LegacyAdminTrendReportView.as_view(), name='legacy-trend-report'),
    path('analysis/consult/', ConsultView.as_view(), name='consult'),
    path('customers/', LegacyAllClientsView.as_view(), name='customer-list'),
    path('customers/<int:pk>/', LegacyAdminClientDetailView.as_view(), name='customer-detail'),
    path('customers/<str:pk>/', LegacyAdminClientDetailView.as_view(), name='customer-detail-legacy-id'),
    path('customers/<int:pk>/assign/', LegacyAdminClientAssignView.as_view(), name='customer-assign'),
    path('customers/<str:pk>/assign/', LegacyAdminClientAssignView.as_view(), name='customer-assign-legacy-id'),
    path('customers/<int:pk>/diagnosis-card/', LegacyDesignerDiagnosisCardView.as_view(), name='customer-diagnosis-card'),
    path('customers/<str:pk>/diagnosis-card/', LegacyDesignerDiagnosisCardView.as_view(), name='customer-diagnosis-card-legacy-id'),
    path('customers/<int:pk>/consultation-note/', LegacyConsultationNoteCreateView.as_view(), name='customer-consultation-note'),
    path('customers/<str:pk>/consultation-note/', LegacyConsultationNoteCreateView.as_view(), name='customer-consultation-note-legacy-id'),
    path('customers/<int:pk>/customer-note/', LegacyCustomerProfileNoteView.as_view(), name='customer-profile-note'),
    path('customers/<str:pk>/customer-note/', LegacyCustomerProfileNoteView.as_view(), name='customer-profile-note-legacy-id'),
    path('admin/auth/register/', AdminRegisterView.as_view(), name='admin-register'),
    path('admin/auth/login/', AdminLoginView.as_view(), name='admin-login'),
    path('admin/auth/refresh/', AdminRefreshView.as_view(), name='admin-refresh'),
    path('admin/auth/me/', AdminProfileView.as_view(), name='admin-profile'),
    path('admin/dashboard/', AdminDashboardView.as_view(), name='admin-dashboard'),
    path('admin/clients/active/', ActiveClientSessionsView.as_view(), name='admin-active-clients'),
    path('admin/clients/', AllClientsView.as_view(), name='admin-clients'),
    path('admin/clients/detail/', AdminClientDetailView.as_view(), name='admin-client-detail'),
    path('admin/clients/recommendations/', AdminClientRecommendationView.as_view(), name='admin-client-recommendations'),
    path('admin/consultations/note/', ConsultationNoteView.as_view(), name='admin-consultation-note'),
    path('admin/consultations/close/', ConsultationCloseView.as_view(), name='admin-consultation-close'),
    path('admin/chatbot/ask/', AdminChatbotAskView.as_view(), name='admin-chatbot-ask'),
    path('admin/ai-health/', AdminAiHealthView.as_view(), name='admin-ai-health'),
    path('admin/trend-report/', AdminTrendReportView.as_view(), name='admin-trend-report'),
    path('admin/style-report/', StyleReportView.as_view(), name='admin-style-report'),
    path('admin/designers/', DesignerListView.as_view(), name='admin-designers'),
]
