# Generated by Django 5.0.14 on 2026-04-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mirrai_app", "0012_client_assigned_at_client_assignment_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyClient",
            fields=[
                (
                    "client_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("shop_id", models.CharField(max_length=255)),
                ("client_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=50)),
                ("created_at", models.TextField()),
                ("updated_at", models.TextField()),
                ("backend_client_id", models.BigIntegerField(blank=True, null=True)),
                ("backend_shop_ref_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "backend_designer_ref_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment_source",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("age_input", models.SmallIntegerField(blank=True, null=True)),
                (
                    "birth_year_estimate",
                    models.SmallIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "client",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LegacyClientAnalysis",
            fields=[
                ("analysis_id", models.IntegerField(primary_key=True, serialize=False)),
                ("client_id", models.CharField(max_length=255)),
                ("designer_id", models.CharField(max_length=255)),
                ("original_image_url", models.TextField(blank=True, null=True)),
                ("face_type", models.CharField(blank=True, max_length=255, null=True)),
                ("face_ratio_vector", models.TextField()),
                ("golden_ratio_score", models.FloatField(blank=True, null=True)),
                ("landmark_data", models.TextField(blank=True, null=True)),
                ("created_at", models.TextField()),
                ("backend_analysis_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "backend_client_ref_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "backend_designer_ref_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "backend_capture_record_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "processed_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("face_count", models.IntegerField(blank=True, null=True)),
                ("error_note", models.TextField(blank=True, null=True)),
                ("updated_at_ts", models.DateTimeField(blank=True, null=True)),
                (
                    "deidentified_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("capture_landmark_snapshot", models.JSONField(blank=True, null=True)),
                ("privacy_snapshot", models.JSONField(blank=True, null=True)),
                (
                    "analysis_image_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("analysis_landmark_snapshot", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "client_analysis",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LegacyClientResult",
            fields=[
                ("result_id", models.IntegerField(primary_key=True, serialize=False)),
                ("analysis_id", models.IntegerField()),
                ("client_id", models.CharField(max_length=255)),
                ("selected_hairstyle_id", models.IntegerField(blank=True, null=True)),
                ("selected_image_url", models.TextField(blank=True, null=True)),
                ("is_confirmed", models.BooleanField()),
                ("created_at", models.TextField()),
                ("updated_at", models.TextField()),
                ("backend_selection_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "backend_consultation_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "backend_client_ref_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("backend_admin_ref_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "backend_designer_ref_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("source", models.CharField(blank=True, max_length=30, null=True)),
                ("survey_snapshot", models.JSONField(blank=True, null=True)),
                ("analysis_data_snapshot", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("is_read", models.BooleanField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "selected_recommendation_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "client_result",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LegacyClientResultDetail",
            fields=[
                ("detail_id", models.IntegerField(primary_key=True, serialize=False)),
                ("result_id", models.IntegerField()),
                ("hairstyle_id", models.IntegerField()),
                ("rank", models.IntegerField()),
                ("similarity_score", models.FloatField()),
                ("final_score", models.FloatField(blank=True, null=True)),
                ("simulated_image_url", models.TextField(blank=True, null=True)),
                ("recommendation_reason", models.TextField(blank=True, null=True)),
                (
                    "backend_recommendation_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "backend_client_ref_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "backend_capture_record_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("batch_id", models.UUIDField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "style_name_snapshot",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("style_description_snapshot", models.TextField(blank=True, null=True)),
                ("keywords_json", models.JSONField(blank=True, null=True)),
                (
                    "sample_image_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("regeneration_snapshot", models.JSONField(blank=True, null=True)),
                ("reasoning_snapshot", models.JSONField(blank=True, null=True)),
                ("is_chosen", models.BooleanField(blank=True, null=True)),
                ("chosen_at", models.DateTimeField(blank=True, null=True)),
                ("is_sent_to_admin", models.BooleanField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at_ts", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "client_result_detail",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LegacyClientSurvey",
            fields=[
                ("survey_id", models.IntegerField(primary_key=True, serialize=False)),
                ("client_id", models.CharField(max_length=255)),
                (
                    "hair_length",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("hair_mood", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "hair_condition",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("hair_color", models.CharField(blank=True, max_length=255, null=True)),
                ("budget", models.CharField(blank=True, max_length=255, null=True)),
                ("preference_vector", models.TextField()),
                ("updated_at", models.TextField()),
                ("backend_survey_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "backend_client_ref_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "target_length",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("target_vibe", models.CharField(blank=True, max_length=50, null=True)),
                ("scalp_type", models.CharField(blank=True, max_length=50, null=True)),
                ("hair_colour", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "budget_range",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("preference_vector_json", models.JSONField(blank=True, null=True)),
                ("created_at_ts", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "client_survey",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LegacyDesigner",
            fields=[
                (
                    "designer_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("shop_id", models.CharField(max_length=255)),
                ("designer_name", models.CharField(max_length=255)),
                ("login_id", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("is_active", models.BooleanField()),
                ("created_at", models.TextField()),
                ("updated_at", models.TextField()),
                ("backend_designer_id", models.BigIntegerField(blank=True, null=True)),
                ("backend_shop_ref_id", models.BigIntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("pin_hash", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "designer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LegacyHairstyle",
            fields=[
                (
                    "hairstyle_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("chroma_id", models.CharField(max_length=255)),
                ("style_name", models.CharField(max_length=255)),
                ("image_url", models.TextField()),
                ("created_at", models.TextField()),
                ("backend_style_id", models.BigIntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("vibe", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hairstyle",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LegacyShop",
            fields=[
                (
                    "shop_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("login_id", models.CharField(max_length=255)),
                ("shop_name", models.CharField(max_length=255)),
                ("biz_number", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "owner_phone",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("password", models.CharField(max_length=255)),
                ("admin_pin", models.CharField(max_length=255)),
                ("created_at", models.TextField()),
                ("updated_at", models.TextField()),
                ("backend_admin_id", models.BigIntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("store_name", models.CharField(blank=True, max_length=100, null=True)),
                ("role", models.CharField(blank=True, max_length=20, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "business_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("consent_snapshot", models.JSONField(blank=True, null=True)),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "shop",
                "managed": False,
            },
        ),
        migrations.RemoveField(
            model_name="consultationrequest",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="consultationrequest",
            name="client",
        ),
        migrations.RemoveField(
            model_name="consultationrequest",
            name="designer",
        ),
        migrations.RemoveField(
            model_name="consultationrequest",
            name="selected_recommendation",
        ),
        migrations.RemoveField(
            model_name="consultationrequest",
            name="selected_style",
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="analysis_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="backend_admin_ref_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="backend_client_ref_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="backend_consultation_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="backend_designer_ref_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="backend_selection_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="client_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="selected_hairstyle_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="selected_image_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="selected_recommendation_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consultationrequest",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consultationrequest",
            name="id",
            field=models.IntegerField(
                db_column="result_id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterModelTable(
            name="consultationrequest",
            table="client_result",
        ),
    ]
