# Generated by Django 5.0.14 on 2026-04-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mirrai_app",
            "0013_legacyclient_legacyclientanalysis_legacyclientresult_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignerDiagnosisCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_ref_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "designer_ref_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "hair_texture",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "damage_level",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("special_notes", models.JSONField(blank=True, default=list)),
                ("special_memo", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_ref_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                (
                    "legacy_client_ref_id",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "designer_diagnosis_cards",
            },
        ),
    ]
