# Generated by Django 5.0.14 on 2026-04-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mirrai_app", "0014_designerdiagnosiscard"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientProfileNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_ref_id", models.BigIntegerField(db_index=True, unique=True)),
                (
                    "legacy_client_ref_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "admin_ref_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "designer_ref_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("content", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "client_profile_notes",
            },
        ),
    ]
