import uuid

import app.models_django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mirrai_app", "0015_clientprofilenote"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="CaptureRecord"),
                migrations.DeleteModel(name="ConsultationRequest"),
                migrations.DeleteModel(name="ClientSessionNote"),
                migrations.DeleteModel(name="FaceAnalysis"),
                migrations.DeleteModel(name="FormerRecommendation"),
                migrations.DeleteModel(name="StyleSelection"),
                migrations.DeleteModel(name="Survey"),
                migrations.DeleteModel(name="Style"),
                migrations.DeleteModel(name="Designer"),
                migrations.DeleteModel(name="Client"),
                migrations.DeleteModel(name="AdminAccount"),
                migrations.DeleteModel(name="DesignerDiagnosisCard"),
                migrations.DeleteModel(name="ClientProfileNote"),
                migrations.CreateModel(
                    name="AdminAccount",
                    fields=[
                        ("id", models.UUIDField(db_column="shop_id", default=uuid.uuid4, primary_key=True, serialize=False)),
                        ("login_id", models.CharField(blank=True, max_length=50, null=True, unique=True)),
                        ("shop_name", models.CharField(blank=True, max_length=100, null=True)),
                        ("biz_number", models.CharField(blank=True, max_length=20, null=True, unique=True)),
                        ("owner_phone", models.CharField(blank=True, max_length=20, null=True)),
                        ("password", models.CharField(blank=True, max_length=255, null=True)),
                        ("admin_pin", models.CharField(default=app.models_django.default_admin_pin_hash, max_length=255)),
                        ("created_at", models.DateTimeField(blank=True, null=True)),
                        ("updated_at", models.DateTimeField(blank=True, null=True)),
                        ("backend_admin_id", models.BigIntegerField(blank=True, null=True)),
                        ("name", models.CharField(blank=True, max_length=50, null=True)),
                        ("store_name", models.CharField(blank=True, max_length=100, null=True)),
                        ("role", models.CharField(blank=True, default="owner", max_length=20, null=True)),
                        ("phone", models.CharField(blank=True, max_length=20, null=True)),
                        ("business_number", models.CharField(blank=True, max_length=30, null=True)),
                        ("password_hash", models.CharField(blank=True, max_length=255, null=True)),
                        ("is_active", models.BooleanField(blank=True, default=True, null=True)),
                        ("consent_snapshot", models.JSONField(blank=True, default=dict, null=True)),
                        ("consented_at", models.DateTimeField(blank=True, null=True)),
                    ],
                    options={"db_table": "shop"},
                ),
                migrations.CreateModel(
                    name="Client",
                    fields=[
                        ("id", models.UUIDField(db_column="client_id", default=uuid.uuid4, primary_key=True, serialize=False)),
                        ("client_name", models.CharField(max_length=50)),
                        ("phone", models.CharField(max_length=20)),
                        ("gender", models.CharField(blank=True, max_length=10, null=True)),
                        ("created_at", models.DateTimeField(blank=True, null=True)),
                        ("updated_at", models.DateTimeField(blank=True, null=True)),
                        ("backend_client_id", models.BigIntegerField(blank=True, null=True)),
                        ("backend_shop_ref_id", models.BigIntegerField(blank=True, null=True)),
                        ("backend_designer_ref_id", models.BigIntegerField(blank=True, null=True)),
                        ("name", models.CharField(blank=True, max_length=50, null=True)),
                        ("assigned_at", models.DateTimeField(blank=True, null=True)),
                        ("assignment_source", models.CharField(blank=True, max_length=30, null=True)),
                        ("age_input", models.SmallIntegerField(blank=True, null=True)),
                        ("birth_year_estimate", models.SmallIntegerField(blank=True, null=True)),
                        ("shop", models.ForeignKey(db_column="shop_id", on_delete=django.db.models.deletion.CASCADE, to="mirrai_app.adminaccount")),
                    ],
                    options={"db_table": "client"},
                ),
                migrations.CreateModel(
                    name="Designer",
                    fields=[
                        ("id", models.UUIDField(db_column="designer_id", default=uuid.uuid4, primary_key=True, serialize=False)),
                        ("designer_name", models.CharField(max_length=50)),
                        ("login_id", models.CharField(max_length=50, unique=True)),
                        ("password", models.CharField(max_length=255)),
                        ("is_active", models.BooleanField(default=True)),
                        ("created_at", models.DateTimeField(blank=True, null=True)),
                        ("updated_at", models.DateTimeField(blank=True, null=True)),
                        ("backend_designer_id", models.BigIntegerField(blank=True, null=True)),
                        ("backend_shop_ref_id", models.BigIntegerField(blank=True, null=True)),
                        ("name", models.CharField(blank=True, max_length=50, null=True)),
                        ("phone", models.CharField(blank=True, max_length=20, null=True)),
                        ("pin_hash", models.CharField(blank=True, max_length=255, null=True)),
                        ("shop", models.ForeignKey(db_column="shop_id", on_delete=django.db.models.deletion.CASCADE, to="mirrai_app.adminaccount")),
                    ],
                    options={"db_table": "designer"},
                ),
                migrations.CreateModel(
                    name="Style",
                    fields=[
                        ("id", models.AutoField(db_column="hairstyle_id", primary_key=True, serialize=False)),
                        ("chroma_id", models.CharField(max_length=100, unique=True)),
                        ("style_name", models.CharField(max_length=100)),
                        ("image_url", models.CharField(max_length=500)),
                        ("created_at", models.DateTimeField(blank=True, null=True)),
                        ("backend_style_id", models.BigIntegerField(blank=True, null=True)),
                        ("name", models.CharField(blank=True, max_length=100, null=True)),
                        ("vibe", models.CharField(blank=True, max_length=50, null=True)),
                        ("description", models.TextField(blank=True, null=True)),
                    ],
                    options={"db_table": "hairstyle"},
                ),
                migrations.CreateModel(
                    name="Survey",
                    fields=[
                        ("id", models.AutoField(db_column="survey_id", primary_key=True, serialize=False)),
                        ("hair_length", models.CharField(blank=True, max_length=20, null=True)),
                        ("hair_mood", models.CharField(blank=True, max_length=20, null=True)),
                        ("hair_condition", models.CharField(blank=True, max_length=20, null=True)),
                        ("hair_color", models.CharField(blank=True, max_length=20, null=True)),
                        ("budget", models.CharField(blank=True, max_length=20, null=True)),
                        ("preference_vector", models.TextField(blank=True, null=True)),
                        ("updated_at", models.DateTimeField(blank=True, null=True)),
                        ("backend_survey_id", models.BigIntegerField(blank=True, null=True)),
                        ("backend_client_ref_id", models.BigIntegerField(blank=True, null=True)),
                        ("target_length", models.CharField(blank=True, max_length=50, null=True)),
                        ("target_vibe", models.CharField(blank=True, max_length=50, null=True)),
                        ("scalp_type", models.CharField(blank=True, max_length=50, null=True)),
                        ("hair_colour", models.CharField(blank=True, max_length=50, null=True)),
                        ("budget_range", models.CharField(blank=True, max_length=50, null=True)),
                        ("preference_vector_json", models.JSONField(blank=True, null=True)),
                        ("created_at_ts", models.DateTimeField(blank=True, null=True)),
                        ("client", models.OneToOneField(db_column="client_id", on_delete=django.db.models.deletion.CASCADE, to="mirrai_app.client")),
                    ],
                    options={"db_table": "client_survey"},
                ),
                migrations.CreateModel(
                    name="DesignerDiagnosisCard",
                    fields=[
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("admin_ref_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                        ("designer_ref_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                        ("hair_texture", models.CharField(blank=True, default="", max_length=20)),
                        ("damage_level", models.CharField(blank=True, default="", max_length=20)),
                        ("special_notes", models.JSONField(blank=True, default=list)),
                        ("special_memo", models.TextField(blank=True, default="")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("client_ref_id", models.BigIntegerField(db_index=True, unique=True)),
                        ("legacy_client_ref_id", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                    ],
                    options={"db_table": "designer_diagnosis_cards"},
                ),
                migrations.CreateModel(
                    name="ClientProfileNote",
                    fields=[
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("client_ref_id", models.BigIntegerField(db_index=True, unique=True)),
                        ("legacy_client_ref_id", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                        ("admin_ref_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                        ("designer_ref_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                        ("content", models.TextField(blank=True, default="")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={"db_table": "client_profile_notes"},
                ),
            ],
        ),
    ]
