from django.shortcuts import render
from django.urls import path
from django.views.generic import RedirectView

from app.front_views import (
    admin_dashboard_page,
    admin_login_page,
    admin_signup_page,
    client_camera_page,
    client_login_page,
    client_menu_page,
    client_recommendation_page,
    client_recommendation_history_page,
    client_trend_page,
    customer_resume_page,
    customer_reanalysis_start_page,
    customer_consultation_complete_page,
    client_survey_page,
    designer_management_page,
    designer_delete_page,
    designer_signup_page,
    designer_dashboard_page,
    designer_logout_page,
    enter_partner_dashboard,
    health_check,
    home_page,
    logout_page,
    customer_logout_page,
    partner_verify,
    partner_designer_list,
    privacy_policy_page,
    terms_page,
)


urlpatterns = [
    path("", home_page, name="index"),
    path("health/", health_check, name="health-check"),
    path("docs/", lambda r: render(r, "pages/home.html"), name="docs"),
    path("terms/", terms_page, name="terms"),
    path("privacy-policy/", privacy_policy_page, name="privacy_policy"),
    path("customer/", client_login_page, name="customer_index"),
    path("customer/continue/", customer_resume_page, name="customer_resume"),
    path("customer/menu/", client_menu_page, name="customer_menu"),
    path("customer/survey/", client_survey_page, name="customer_survey"),
    path("customer/survey/male/", client_survey_page, {"gender": "male"}, name="customer_survey_male"),
    path("customer/survey/female/", client_survey_page, {"gender": "female"}, name="customer_survey_female"),
    path("customer/camera/", client_camera_page, name="customer_camera"),
    path("customer/trend/", client_trend_page, name="customer_trend"),
    path("customer/consultation/complete/", customer_consultation_complete_page, name="customer_consultation_complete"),
    path("customer/recommendations/", client_recommendation_page, name="customer_result"),
    path("customer/history/", client_recommendation_history_page, name="customer_history"),
    path("customer/result/", RedirectView.as_view(pattern_name="customer_history", permanent=False), name="customer_result_legacy"),
    path("customer/logout/", customer_logout_page, name="customer_logout"),
    path("demo/discovery/", lambda r: render(r, "demo/discovery.html"), name="demo_discovery"),
    path("partner/", admin_login_page, name="partner_index"),
    path("partner/login/", admin_login_page, name="partner_login"),
    path("partner/signup/", admin_signup_page, name="partner_signup"),
    path("partner/designer-select/", lambda r: render(r, "admin/designer_select.html"), name="partner_designer_select"),
    path("partner/designers/", designer_management_page, name="partner_designer_management"),
    path("partner/designers/new/", designer_signup_page, name="partner_designer_signup"),
    path("partner/designers/delete/", designer_delete_page, name="partner_designer_delete"),
    path("partner/verify/", partner_verify, name="partner_verify"),
    path("partner/dashboard/enter/", enter_partner_dashboard, name="partner_dashboard_enter"),
    path("partner/dashboard/", admin_dashboard_page, name="partner_dashboard"),
    path("partner/staff/", designer_dashboard_page, name="partner_staff_dashboard"),
    path("partner/customer-detail/<int:pk>/", lambda r, pk: render(r, "admin/customer_detail.html", {"client_id": pk}), name="partner_customer_detail"),
    path("partner/customer-detail/<int:pk>/reanalysis/", customer_reanalysis_start_page, name="partner_customer_reanalysis_start"),
    path("partner/logout/", logout_page, name="partner_logout"),
    path("partner/staff/logout/", designer_logout_page, name="designer_logout"),
    path("logout/", logout_page, name="logout"),
    path("api/v1/designers/", partner_designer_list, name="partner_designer_list"),
    # Legacy aliases kept for older links and docs.
    path("client/login/", client_login_page, name="client-login-shell"),
    path("client/survey/", client_survey_page, name="client-survey-shell"),
    path("client/recommendations/", client_recommendation_page, name="client-recommendation-shell"),
    path("admin-panel/login/", RedirectView.as_view(pattern_name="partner_index", permanent=False), name="admin-login-shell"),
    path("admin-panel/dashboard/", RedirectView.as_view(pattern_name="partner_index", permanent=False), name="admin-dashboard-shell"),
]
